### ISSUE TITLE
About the implementation of dads.

### ISSUE THREAD

**Issue by gaiyi7788** [ademiadeniji/irm#1]
Thank you for your outstanding work and for open sourcing the experimental code.

I am new to the field of skill discovery, and I found that in your code implementation, CIC uses ddpg update, while DADS uses sac.

I know you followed the implementation of the original paper in doing so, but I wonder if using different RL algorithms for updates would make a big difference in the results of skill discovery.

Since I noticed that ddpg is used uniformly in URLB for updating, I wonder if I could also use ddpg for updating DADS to ensure the uniformity of the policy update algorithm.

I hope you can help me with this! Thank you very much!

**Comment by ademiadeniji** [comment]
Thanks for your kind words and sorry for the delayed response!

I believe it is fine to implement DADS with DDPG/TD3 or many other RL
algorithms. Results may of course vary, but I think the essential part of
DADS is the empowerment objective, not the underlying RL algorithm. Feel
free to follow up with more questions!

Best,
Ademi

**Comment by gaiyi7788** [comment]
Thank you for your generous reply!
